In [1]:
import pandas

Načtení dat o zaměstnancích z CSV:

In [2]:
zam_praha = pandas.read_csv('zam_praha.csv')
zam_plzen = pandas.read_csv('zam_plzen.csv')
zam_liberec = pandas.read_csv('zam_liberec.csv')

Přidání nového sloupce 'mesto' do každé tabulky:

In [3]:
zam_praha['mesto'] = 'Praha'
zam_plzen['mesto'] = 'Plzen'
zam_liberec['mesto'] = 'Liberec'

Nová tabulka se všemi zaměstnanci:

In [4]:
zamestnanci = pandas.concat([zam_praha, zam_plzen, zam_liberec])

Načtení platů z CSV souboru a propojení s tabulkou zaměstnanců:

In [5]:
platy = pandas.read_csv('platy_2021_02.csv')
platy.head()

   cislo_zamestnance     plat
0                  3  54900.0
1                  6  54800.0
2                  7  36400.0
3                  8  47900.0
4                 16  34200.0

In [6]:
platy_zamestnancu = pandas.merge(zamestnanci, platy, on=['cislo_zamestnance'], how="outer")
platy_zamestnancu

,jmeno,prijimeni,telefonni_cislo,cislo_zamestnance,mesto,plat
0,Brian,Hall,+421 949 656 098,30,Praha,33500.0
1,Marta,Kolářová,730 456 163,32,Praha,53000.0
2,John,Moravec,725 092 179,33,Praha,38400.0
3,Dominika,Kopecká,722 747 626,34,Praha,36800.0
4,Marcel,Hájek,+421 902 928 669,35,Praha,NaN
5,Milada,Hernandez,773 373 704,38,Praha,32600.0
6,Catherine,Bender,604 068 460,40,Praha,32800.0
7,Olga,Němcová,+421 914 172 243,41,Praha,49300.0
8,Jeffrey,Šťastný,607 628 821,44,Praha,52000.0
9,Kamila,Říhová,+421 948 396 069,47,Praha,40700.0
10,Jaromír,Miller,+421 912 615 902,49,Praha,58400.0
11,Christopher,Zeman,+421 948 150 084,51,Praha,37100.0
12,Karolína,Short,721 589 083,53,Praha,NaN
13,Michelle,Vlčková,+421 41 720 7806,54,Praha,NaN
14,Jeffrey,Pospíšil,+421 55 491 6940,56,Praha,39300.0
15,Ladislav,Blažek,+421 910 274 975,57,Praha,36800.0
16,John,Bailey,775 021 116,58,Praha,NaN
17,William,Shelton,+421 47 745 8219,60,Praha,NaN
18,Miroslava,Veselá,774 029 254,62,Praha,NaN
19,William,Alexander,+421 949 106 724,63,Praha,31400.0
20,Kimberly,Bass,+421 912 169 840,64,Praha,36900.0
21,Nathan,Svoboda,728 710 923,66,Praha,NaN
22,Luděk,Bartoš,+421 940 700 326,69,Praha,32600.0
23,Dillon,Black,734 300 978,70,Praha,52600.0
24,Robert,Říha,727 351 984,72,Praha,NaN
25,Steve,Šimek,604 966 101,74,Praha,49300.0
26,Theresa,Kučerová,+421 48 528 0081,76,Praha,55400.0
27,Marta,Butler,+421 944 196 827,78,Praha,52600.0
28,Samantha,Kadlecová,+421 904 841 543,80,Praha,57700.0
29,Stacy,Pospíšilová,727 293 880,3,Plzen,54900.0
30,Matěj,Král,770 787 377,6,Plzen,54800.0
31,Amanda,Wilson,+421 52 656 7231,7,Plzen,36400.0
32,Angel,Wilson,+421 52 135 2491,8,Plzen,47900.0
33,Jindřich,Howell,+421 39 043 0948,10,Plzen,NaN
34,Alexander,Martinez,721 195 689,13,Plzen,NaN
35,Radim,Kopecký,+421 917 371 226,16,Plzen,34200.0
36,Miroslav,Reed,774 829 074,18,Plzen,35400.0
37,Emilie,Powell,731 380 539,21,Plzen,54200.0
38,Nikola,Wade,726 763 154,22,Plzen,34400.0
39,Katherine,Reed,726 214 968,23,Plzen,39000.0
40,Kayla,Urbanová,737 772 985,24,Plzen,44200.0
41,Roman,Moreno,722 284 985,26,Plzen,59600.0
42,Bohumila,Smith,608 121 912,27,Plzen,45100.0
43,Blažena,Smith,+421 51 828 2591,28,Plzen,38100.0
44,Phillip,Malý,731 594 560,29,Plzen,48900.0
45,Nela,Šťastná,728 454 176,83,Liberec,46500.0
46,Heather,Marková,604 404 522,84,Liberec,38600.0
47,Krista,Procházková,+421 50 444 5544,85,Liberec,44200.0
48,Jennifer,Brown,775 545 190,86,Liberec,NaN
49,Ladislava,Blackwell,+421 913 487 200,87,Liberec,49900.0
50,Robert,Macias,+421 49 929 6856,88,Liberec,NaN
51,Dana,Reyes,+421 904 153 942,90,Liberec,41100.0
52,Vasyl,Veselý,603 759 413,92,Liberec,48100.0
53,Randy,Veselý,777 149 125,95,Liberec,31600.0
54,Audrey,Allen,+421 908 839 506,96,Liberec,50200.0
55,Ivan,Bartoš,603 226 051,99,Liberec,NaN

Porovnání rozeměrů tabulek před a po spojení:

In [7]:
zamestnanci.shape

(56, 5)

In [8]:
platy_zamestnancu.shape

(56, 6)

Chybějící plat u zaměstnance za únor znamená, že již není aktivním zam.:

In [9]:
platy_zamestnancu[platy_zamestnancu['plat'].isna()]

        jmeno prijimeni   telefonni_cislo  cislo_zamestnance    mesto  plat
4      Marcel     Hájek  +421 902 928 669                 35    Praha   NaN
12   Karolína     Short       721 589 083                 53    Praha   NaN
13   Michelle   Vlčková  +421 41 720 7806                 54    Praha   NaN
16       John    Bailey       775 021 116                 58    Praha   NaN
17    William   Shelton  +421 47 745 8219                 60    Praha   NaN
18  Miroslava    Veselá       774 029 254                 62    Praha   NaN
21     Nathan   Svoboda       728 710 923                 66    Praha   NaN
24     Robert      Říha       727 351 984                 72    Praha   NaN
33   Jindřich    Howell  +421 39 043 0948                 10    Plzen   NaN
34  Alexander  Martinez       721 195 689                 13    Plzen   NaN
48   Jennifer     Brown       775 545 190                 86  Liberec   NaN
50     Robert    Macias  +421 49 929 6856                 88  Liberec   NaN
55       Ivan    Bartoš       603 226 051                 99  Liberec   NaN

Aktivní zaměstnanci firmy:

In [10]:
platy_zamestnancu.dropna(subset=['plat'])

,jmeno,prijimeni,telefonni_cislo,cislo_zamestnance,mesto,plat
0,Brian,Hall,+421 949 656 098,30,Praha,33500.0
1,Marta,Kolářová,730 456 163,32,Praha,53000.0
2,John,Moravec,725 092 179,33,Praha,38400.0
3,Dominika,Kopecká,722 747 626,34,Praha,36800.0
5,Milada,Hernandez,773 373 704,38,Praha,32600.0
6,Catherine,Bender,604 068 460,40,Praha,32800.0
7,Olga,Němcová,+421 914 172 243,41,Praha,49300.0
8,Jeffrey,Šťastný,607 628 821,44,Praha,52000.0
9,Kamila,Říhová,+421 948 396 069,47,Praha,40700.0
10,Jaromír,Miller,+421 912 615 902,49,Praha,58400.0
11,Christopher,Zeman,+421 948 150 084,51,Praha,37100.0
14,Jeffrey,Pospíšil,+421 55 491 6940,56,Praha,39300.0
15,Ladislav,Blažek,+421 910 274 975,57,Praha,36800.0
19,William,Alexander,+421 949 106 724,63,Praha,31400.0
20,Kimberly,Bass,+421 912 169 840,64,Praha,36900.0
22,Luděk,Bartoš,+421 940 700 326,69,Praha,32600.0
23,Dillon,Black,734 300 978,70,Praha,52600.0
25,Steve,Šimek,604 966 101,74,Praha,49300.0
26,Theresa,Kučerová,+421 48 528 0081,76,Praha,55400.0
27,Marta,Butler,+421 944 196 827,78,Praha,52600.0
28,Samantha,Kadlecová,+421 904 841 543,80,Praha,57700.0
29,Stacy,Pospíšilová,727 293 880,3,Plzen,54900.0
30,Matěj,Král,770 787 377,6,Plzen,54800.0
31,Amanda,Wilson,+421 52 656 7231,7,Plzen,36400.0
32,Angel,Wilson,+421 52 135 2491,8,Plzen,47900.0
35,Radim,Kopecký,+421 917 371 226,16,Plzen,34200.0
36,Miroslav,Reed,774 829 074,18,Plzen,35400.0
37,Emilie,Powell,731 380 539,21,Plzen,54200.0
38,Nikola,Wade,726 763 154,22,Plzen,34400.0
39,Katherine,Reed,726 214 968,23,Plzen,39000.0
40,Kayla,Urbanová,737 772 985,24,Plzen,44200.0
41,Roman,Moreno,722 284 985,26,Plzen,59600.0
42,Bohumila,Smith,608 121 912,27,Plzen,45100.0
43,Blažena,Smith,+421 51 828 2591,28,Plzen,38100.0
44,Phillip,Malý,731 594 560,29,Plzen,48900.0
45,Nela,Šťastná,728 454 176,83,Liberec,46500.0
46,Heather,Marková,604 404 522,84,Liberec,38600.0
47,Krista,Procházková,+421 50 444 5544,85,Liberec,44200.0
49,Ladislava,Blackwell,+421 913 487 200,87,Liberec,49900.0
51,Dana,Reyes,+421 904 153 942,90,Liberec,41100.0
52,Vasyl,Veselý,603 759 413,92,Liberec,48100.0
53,Randy,Veselý,777 149 125,95,Liberec,31600.0
54,Audrey,Allen,+421 908 839 506,96,Liberec,50200.0

Průměrný plat zaměstnanců dle jednotlivých měst:

In [11]:
prumerny_plat = platy_zamestnancu.dropna(subset=['plat'])

In [12]:
prumerny_plat.groupby("mesto")["plat"].mean()

mesto
Liberec    43775.000000
Plzen      44792.857143
Praha      43295.238095
Name: plat, dtype: float64

Zadání 2:
Načtení dat z CSV a uložení do tabulky:

In [13]:
vykazy = pandas.read_csv('vykazy.csv')

In [14]:
vykazy.head()

         date  hours project  emloyee_id
0  2021-02-01    2.5     F30          13
1  2021-02-01    3.4     W05          70
2  2021-02-01    2.1     JL9          72
3  2021-02-01    5.2     F30           3
4  2021-02-01    2.4     TE1          54

Agregace dat a celkový počet vykázaných hodin za jednotlivé projekty:

In [15]:
vykazy.groupby('project')['hours'].sum()

project
F30    21.5
JL9     2.1
TE1    16.0
W05    30.5
YLI    31.0
Name: hours, dtype: float64